# שם התלמיד

....................

<p dir = rtl><b>
שנה את הקוד בתיבות הקוד בהם רשום:
 Add your code here
</p>

<h1 dir = rtl>
ספריית Numpy
</h1>

<p dir=rtl>
 Numpy היא אחת מהספריות הבסיסיות ליישום מודלים של למידת מכונה בפייתון. הספריה מאפשרת חישובים יעילים מאוד על וקטורים ומטריצות: יצירה, פעולות אלגברה ליניארית, וכן וקטוריזציה של הקוד.
</p>

<p dir=rtl>בהנחה שספריית numpy  כבר מותקנת אצלכם, או שאתם עובדים על גוגל קולאב,  צריך פשוט לייבא אותה לתוכנית: <br>
</p>

In [1]:
import numpy as np



<p dir=rtl>
 טיפוס הנתונים הבסיסי של numpy  הוא סוג של מערך (array) מיוחד הנקרא: numpy.ndarray.
<br>
בעזרת טיפוס זה ניצור וקטורים, כלומר מערך חד ממדי (1D arrays), וכן מטריצות, כלומר מערכים רב ממדיים.
<br>
לעיתים מערכים רב ממדיים אלו נקראים גם טנסורים.
<br>
כמו בכל מערך, גם בnumpy.ndarray, כל האלמנטים\איברים שהמערך מכיל חייבים להיות מאותו טיפוס נתונים. ברירת המחדל היא float64, אך ניתן להעביר לטיפוס מספרי אחר.
<br>
מה שהופך את הndarray  של numpy למערך ״מיוחד״ ושימושי מאוד בלמידת מכונה, הוא שניתן להתייחס אליו כאל וקטור או מטריצה ולבצע עליו באופן פשוט מגוון פעולות חשבוניות מתחום האלגברה ליניארית. כגון מכפלה של וקטור בסקלר (מספר רגיל) מכפלה פנימית של וקטור בוקטור, ווקטור במטריצה, היפוך מטריצה ועוד.
<br>
אבל מעבר לנוחות בביצוע הפעולות הללו, היתרון הגדול של numpy  זה שזו ספרייה המבצעת את הפעולות הללו בצורה אופטימלית מאוד. כלומר, באופן יעיל ביותר.
<br>

</p>


<hr>

<hr>
<h1 dir = rtl>
<b>
1. יצירה של וקטור או מטריצה
</b>
</h1>

<p dir=rtl>
  בחלון הבא נדגים יצירה בסיסית  של וקטור, נבדוק מהו טיפוס הנתונים שלו, וכן נדגים גישה לאלמנט מסויים  בוקטור והשמה לאלמנט מסויים.<br>
</p>

In [ ]:
a = np.array([11, 22, 33])  # Creating a vector

print(a)      # printing the vector
print(type(a)) # printing the data type of the vector
print(a.shape) # Print the shape of the vector
print(a[0],  a[2]) # access individual elements in the vector
a[0] = 5           # Setting a value of a single element of the vector
print(a)      # printing the new vector

[11 22 33]
<class 'numpy.ndarray'>
(3,)
11 33
[ 5 22 33]


<p dir = rtl>
  כעת נדגים יצירה של מטריצה (מערך דו ממדי):<br>
</p>

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Creating a 2 by 3 matrix
b


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b.shape)
print(b[0, 0])   # printing the 1st number in the 1st line of the matrix
print(b[0, 1])   # printing the 1st number in the 2nd line of the matrix
print(b[1, 0])   # printing the 2nd number in the 2nd line of the matrix

(2, 3)
1
2
4


<p dir=rtl>
    לספרייה NUMPY יש בנוסף הרבה פונקציות אשר בונות מיד מטריצות "מוכנות" שמשתמשים בהם הרבה, כמו לדוגמא מטריצת היחידה עליה נפרט בהמשך ומטריצה מלאה באפסים.
</p>

In [ ]:
a = np.zeros((2,2))  # Create a matrix of all zeros 2 by 2
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((2,3))   # Creating a matrix that is only ones
print(b)
print(b.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


<p dir=rtl>
   שימו לב שאפשר לעשות את הפעולה הקודמת גם בדרך של הפעולה הבאה המייצרת מטריצה מלאה במספר כלשהו, פשוט עבור אפס ואחד ישנה פעולה מיוחדת ליצירת מטריצה מלאה בהם. .<br>
</p>

In [ ]:
c = np.full((2,2), 7) # Creating a matrix that is filled with the same number
print(c)

[[7 7]
 [7 7]]


<div dir=rtl>



   יצירה של מטריצה או וקטור בעזרת רשימה. .<br>
</p>

In [ ]:
# Let's define a one-dimensional array
my_list = [10, 20, 50, 60, 70]
print (my_list)
print (type(my_list))



[10, 20, 50, 60, 70]
<class 'list'>


In [ ]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
print (x)
print (type(x))
print(x.shape)

[10 20 50 60 70]
<class 'numpy.ndarray'>
(5,)


<h2 dir = rtl>
תרגיל 1
</h2>
<p dir = rtl>
כתבו קוד היוצר את המערך הבא בגודל $2x4$
</p>


```
[[4 6 8 7]
[20 5 6 9]]
```

In [ ]:
# Add your code here



<hr>
<h1 dir = rtl>
<b>
2. שיטות להשמת ערכים לאברי מערכים
</b>
</h1>


<p dir = rtl>
   יצירה של מטריצה או וקטור בצורה נתונה המלאה בערכים רנדומליים. <br>
</p>

In [ ]:
# "rand()" fills with values from the uniform distribution between 0 and 1
x = np.random.rand(3,4)
x

array([[0.25155797, 0.39815157, 0.91673836, 0.94078073],
       [0.07067755, 0.60622018, 0.64409657, 0.75604672],
       [0.81951735, 0.14231441, 0.35293413, 0.55763856]])

In [ ]:
# "randn()" fills with values from the normal distribution. mean = 0 , std = 1
x = np.random.randn(3,4)
x

array([[-0.9236764 ,  1.35834423, -0.89873263,  0.16195847],
       [ 0.32234761,  2.65172991,  1.10110961,  0.83441334],
       [-0.04562944,  0.42713467,  1.33338887,  0.71594698]])

<p dir = rtl>
הריצו את התא הבא וצפו בסרטון שמסביר מה זה התפלגות נורמלית. צפו בו. 5 דקות
</p>

<iframe width="560" height="315" src="https://www.youtube.com/embed/rzFX5NWojp0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [ ]:
from IPython.display import HTML
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/rzFX5NWojp0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

In [ ]:
# "randint()" fills with integer values within a range
x = np.random.randint(-3 , 3 , 10)
print(x)

[-2 -1 -3 -1  1  0  2 -1 -3  2]


<p dir = rtl>
עשרה ערכים שלמים בתחום שבין 3- ל 3 (לא כולל 3)
</p>

In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
# Create an evenly spaced n values between start value and end value
x = np.linspace(-3 , 3 , 20)
print(x)

[-3.         -2.68421053 -2.36842105 -2.05263158 -1.73684211 -1.42105263
 -1.10526316 -0.78947368 -0.47368421 -0.15789474  0.15789474  0.47368421
  0.78947368  1.10526316  1.42105263  1.73684211  2.05263158  2.36842105
  2.68421053  3.        ]


In [ ]:
# "randn()" fills with values from the normal distribution
x = np.random.randn(10)
x

array([-0.47032717, -0.99220922,  0.983947  , -0.87497339, -0.80097813,
       -0.64584638, -0.14446948,  2.2340586 ,  1.92573905, -0.45862869])

<h2 dir = rtl>
תרגיל 2
</h2>
<p dir = rtl>
השלימו את הקוד בתא הבא. הקוד אמור לקלוט משנה n מהמשתמש וליצור מערך numpy חד ממדי בגודל $1xn$    שאבריו מאותחלים לערכים אקראיים המפוזרים בצורה אחידה בתחום 0-1
</p>

In [ ]:
n = int(input("Please enter a positive integer value: "))
# complete the solution to the mini challenge #2 below:

# Add your code here



<hr>
<h1 dir = rtl>
<b>
3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES
</b>
</h1>

In [ ]:
# Let's define a one-dimensional array
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [ ]:
# Get Length of a numpy array
len(x)

8

In [ ]:
# Get shape
x.shape

(8,)

In [ ]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
print(x)
print(z)


[-30   4  50  60  29  15  22  90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [ ]:
z1 = x.reshape(1,8)
print(z1)
z1.shape

[[-30   4  50  60  29  15  22  90]]


(1, 8)

<p dir = rtl>
שימו לב ש z הוא view דו ממדי של x המקורי. לא נבנה כאן מערך חדש!
</p>

In [ ]:
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

<p dir = rtl>
אם נרצה מערך חדש, נשתמש ב- copy
</p>

In [ ]:
x = np.array(my_list)
z = x.copy()
print(z.flags.owndata)
z = z.reshape(2,4)
print(z.flags.owndata)
x[0] = 9999
print(x)
print(z)

True
False
[9999    4   50   60   29   15   22   90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [ ]:
# Obtain the maximum element (value)
np.max(x)

9999

In [ ]:
# Obtain the minimum element (value)
np.min(x)

4

In [ ]:
# Obtain the location of the max element
np.argmax(x)

0

<h2 dir = rtl>
תרגיל 3
</h2>
<p dir = rtl>
כתבו קוד הבונה מערך נמפיי בגודל $4x5$ שערכיו בין 300 ל 500 במרווחים של 10
<br>
הדרכה: צרו מערך חד ממשי ושנו את ה shape שלו

In [ ]:
# Add your code here



<p dir = rtl>
אם תדפיסו את המערך אחרי שיצרתם אותו, אתם אמורים לקבל:
</p>
<p>
<code>
[[300 310 320 330 340] <br>
 [350 360 370 380 390] <br>
 [400 410 420 430 440] <br>
 [450 460 470 480 490]]<br>
</code>
</p>

<h2 dir = rtl>
תרגיל 4
</h2>
<p dir = rtl>
כתבו קוד היוצר מערך נמפיי בגודל $20x20$ שערכיו שלמים בטווח 1000- עד 1000 (לא כולל 1000, כן כולל 1000-).
<br>
הדפיסו את הערך המקסימלי במערך, את הערך המינימלי במערל ואת הערך הממוצע שלו
</p>

In [ ]:
np.random.seed(16) # Leave this line of code, do not change it

# Add your code here



<p dir = rtl>
אם תדפיסו את המינימום, מקסימום והממוצע, אתם אמורים לקבל:</p>
<p>
<code>
max: 979 , min: -994 , mean: -53.745
</code>
</p>


<h1 dir = rtl>
<b>
   4. חיתוך וקטורים ומטריצות
</b>
</h2>

<p dir=rtl>
  ספריית numpy מספקת לנו שלל של דרכים לפנות ולערוך ערכים במיקומים ספציפים של המטריצה .<br>
</p>

In [2]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [6]:
# Starting from the first index 1 (the 2nd elemnet) up until and NOT inlcluding the elment at index 4
#x[1:4]


array([20, 40])

In [7]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [8]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[9, 5, 4, 6, 3],
       [7, 6, 1, 1, 4],
       [9, 7, 1, 7, 4],
       [7, 3, 2, 6, 7],
       [9, 5, 9, 3, 1]])

In [9]:
# Get a row from a mtrix
matrix[2]

array([9, 7, 1, 7, 4])

In [10]:
# Get one element
matrix[0 , 2]

4

<p dir = rtl>
שורות 0,1,2
</p>

In [11]:
mini_matrix = matrix[:3]
mini_matrix

array([[9, 5, 4, 6, 3],
       [7, 6, 1, 1, 4],
       [9, 7, 1, 7, 4]])

<p dir = rtl>
שורות 2 עד הסוף:
</p>

In [12]:
mini_matrix = matrix[2:]
mini_matrix

array([[9, 7, 1, 7, 4],
       [7, 3, 2, 6, 7],
       [9, 5, 9, 3, 1]])

<p dir = rtl>
כל השורות, עמודות 0 ו- 1
</p>

In [13]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[9, 5],
       [7, 6],
       [9, 7],
       [7, 3],
       [9, 5]])

<p dir = rtl>
כל השורות, עמודות 2 עד הסוף:
</p>

In [16]:
mini_matrix = matrix[:, 2:]
mini_matrix


array([[4, 6, 3],
       [1, 1, 4],
       [1, 7, 4],
       [2, 6, 7],
       [9, 3, 1]])

In [17]:


#Create the following matrix with shape (3, 4)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the value:
#[[2 3]
#[6 7]]
b = a[:2, 1:3]
  #The first part (:2) refers to the slicing of the matrix, it takes the first two line of th metrix.
  #The second part (1:3) refers to the slicing of the two line we just pulled, it takes the numbers between the index 1-3.
print(b)

[[2 3]
 [6 7]]


<p dir=rtl>
    שימו לב חיתוך של מטריצה הוא כמו צפייה בחלק ספיציפי בה, ואם נשנה את החלק הזה  הוא ישנה את המטריצה המקורית
</p>

In [18]:
print(a[0, 1])
b[0, 0] = 77         # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


In [ ]:
print(a)
print(b)

<h2 dir = rtl>
תרגיל 5
</h2>
<p dir = rtl>
במטריצה הבאה
</p>
<ul dir = rtl>
<li>
עדכנו את ערכי השורה האחרונה להיות 1-
</li>
<li>
הכפילו את אברי תת המטריצה בגודל $2x2$ בפינה הימנית העליונה, ב- 2

<p dir = rtl>
אם תדפיסו את המטריצה אחרי השינויים, אתם אמורים לקבל:</p>
<p>
<code>
[[ 2 30 20 -4 -8] <br>
 [ 3  4 40 -6 -4] <br>
 [-3  4 -6 90 10] <br>
 [25 45 34 22 12] <br>
 [-1 -1 -1 -1 -1]] <br>
</code>
</p>

In [ ]:
X = np.array( [[2, 30, 20, -2, -4],
               [3, 4,  40, -3, -2],
               [-3, 4, -6, 90, 10],
               [25, 45, 34, 22, 12],
               [13, 24, 22, 32, 37]])

# Add your code here





<p dir=rtl>
ניתן לפנות למשתנים במטריצה בפנייה בוליאנית. בפניה כזו מעבירים מטריצה בגודל זהה המורכבת מ׳אמת׳ ו׳שקר׳ והביטוי יחזיר את כל האלמנים במקום של ה׳אמת׳. ניתן לייצר מטריצה בוליאנית בגודל זהה על ידי הפעלת תנאי על המטריצה. על כן פנייה זאת מאוד שימושית כאשר רוצים להשאיר רק נתונים מסוימים שעונים
על הקריטריונים הרצויים לך. לדוגמא: <br>
</p>

In [19]:

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)  # Find the elements of ׳a׳ that are bigger than 2.
                    # this returns a matrix of Booleans of the same
                    # shape as matrix "a", where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [20]:
# if we whould like to print all the numbers that are bigger the 2 and not just if they are bigger then 2 add the matrix name and []
print(a[a > 2])

[3 4 5 6]


<h2 dir = rtl>
תרגיל 6
</h2>
<p dir = rtl>
במטריצה הבאה החליפו את כל המספרים השליליים ב 0 ואחר כך את כל המספרים האי-זוגיים ב 25
</p>

<p dir = rtl>
אם תדפיסו את המטריצה אחרי השינויים, אתם אמורים לקבל:</p>
<p>
<code>
[[ 2 30 20  0  0] <br>
 [25  4 40  0  0] <br>
 [ 0  4  0 90 10] <br>
 [25 25 34 22 12] <br>
 [25 24 22 32 25]] <br>
</code>
</p>

In [ ]:
X = np.array( [[2, 30, 20, -2, -4],
               [3, 4,  40, -3, -2],
               [-3, 4, -6, 90, 10],
               [25, 45, 34, 22, 12],
               [13, 24, 22, 32, 37]])

# Add your code here




<p dir = rtl>
    חשוב לזכור שכל מטריצה היא אוסף של משתנים מאותו סוג. בנוסף בNUMPY כל עוד המתכנת לא מצהיר על סוגי המשתנים במטריצה NUMPY תבחר אותם לבד, כמו שרואים בדוגמא:
</p>

In [21]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1.0, 2.0], dtype=np.int64)  # Force a particular datatype - inte

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


<p dir=rtl>
    לקריאה על כל סוגי המשתנים בNUMPY לחצו על הקישור הזה :
    <a href = http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html>Numpy Data Types</a>
</p>

<h1 dir = rtl>
<b>
5. פעולות אריתמטיות על וקטורים ומטריצות
</b>
</h1>

<p dir=rtl>
 פונקציות חישוביות בסיסיות במטריצות פועלות כאשר שני המטריצות מאותו צורה ואז הפעולות מתבצאות אלמנט מול אלמנט לפי מיקום. אפשר להפעיל פונקציות אלו כפונקציות או על ידי שימוש באופרטורים החשבוניים הרגילים:<br>
</p>

In [22]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print (f"x = \n {x}")
print (f"\ny = \n {y}")
# Elementwise sum

print ("\nx + y =")
print(x + y) # as operator
print()

print(np.add(x, y)) # as a function

x = 
 [[1 2]
 [3 4]]

y = 
 [[5 6]
 [7 8]]

x + y =
[[ 6  8]
 [10 12]]

[[ 6  8]
 [10 12]]


In [23]:
# Elementwise difference;
print(x - y)
print()
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]

[[-4 -4]
 [-4 -4]]


In [24]:
# Elementwise product;
print(x * y)
print()
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]


In [25]:
# Elementwise division;
print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
# Elementwise square root;
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
# Elementwise power;
print(np.power(x, 2)) # העלאה בריבוע של כל אחד מאיברי המטריצה

[[ 1  4]
 [ 9 16]]


<h1 dir = rtl>
<b>
6. מכפלה פנימית - Dot product
</b>
</h1>
<p dir=rtl>
  בכדי לעשות מכפלה פנימית של מטריצות ו\או וקטורים (באנגלית נקרא inner product או dot product) נקרא לפונקציה המובנת dot כמו בדוגמא למטה:
<p/>

In [28]:
# מכפלה פנימית של שני וקטורים
# שני הוקטורים מוכרחים להיות בעלי אותו מספר מימדים

# נגדיר שני וקטורים
v = np.array([10,5]) # וקטור עם 2 מימדים
w = np.array([2,1]) # וקטור עם 2 מימדים


# את המכפלה אפשר לעשות על ידי כל אחד מהצורות הבאות
print(v)
print(w)
print(v.dot(w))
print(np.dot(v, w))



[10  5]
[2 1]
25
25


<p dir = rtl>
מאחר ופעולת המכפלה בין וקטורים ומטריצות נמצאת בשימוש נרחב מאוד, החל מגרסת פיתון 3.5 (נכנסה לעבודה ב2016) במקום לקרוא לפונקציה המובנת  dot ניתן להשתמש באופרטור ״@״ על מנת לבצע מכפלה זו.
</p>


In [ ]:
print(v)
print(w)
print(v @ w)

<p dir=rtl>
כיום משתמשים ב״@״ באופן כמעט בלעדי. עם זאת, בדוגמאות רבות הקיימות ברשת עוד לפני 2016 תמצאו כתיב של dot  
</p>


In [29]:
# מכפלה פנימית של וקטור ומטריצה
#מימד הוקטור חייב להיות זהה למימד העמודות של המטריצה

A = np.array([[1,2],[3,4], [5,5],[6,0]]) # מטריצה  4 על 2
print(f"A = \n{A}")
print(f"v = {v}")
print(f"w = {w}")


print(f"A @ w = {A@w}")
print(f"A @ v = {A@v}")


A = 
[[1 2]
 [3 4]
 [5 5]
 [6 0]]
v = [10  5]
w = [2 1]
A @ w = [ 4 10 15 12]
A @ v = [20 50 75 60]


<h1 dir = rtl>
<b>
7. היפוך מטריצה - Transpose
</b>
</h1>

In [30]:
A = np.array([[1,2],[3,4], [5,5],[6,0]]) # מטריצה  4 על 2
print("A =")
print (A)
print ("\nA.shape = ")
print(A.shape)
print("\nA.T =")
print (A.T)
print ("\nA.T.shape = ")
print(A.T.shape)

A =
[[1 2]
 [3 4]
 [5 5]
 [6 0]]

A.shape = 
(4, 2)

A.T =
[[1 3 5 6]
 [2 4 5 0]]

A.T.shape = 
(2, 4)


In [31]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


<p dir=rtl>
 בnumpy  יש אבחנה בין וקטור למטריצה חד ממדית.
<br>
הshape  של וקטור בעל 5 אלמנטים יראה כך: (5,)
<br>
בעוד במטריצה חד ממדית הshape  יהיה:  .(5,1)
<br>
</p>

In [32]:
c = np.array([3,5,7])
print(c.shape)
print(c)
d = np.array([[3],[5],[7]])
print(d.shape)
print(d)

(3,)
[3 5 7]
(3, 1)
[[3]
 [5]
 [7]]


<p dir=rtl>
 אבחנה זו חשובה מאחר וכאשר מנסים להכפיל וקטור במטריצה, כל עוד אחד מממדי המטריצה תואם למימד הוקטור, numpy  יבצע את הכפלה.
<br>
לעומת זאת, אם ננסה להכפיל מטריצה חד ממדית, נצטרך לדאוג לעשות לה transpose בהתאם לצורת המטריצה הדו ממדית בה אנו רוצים לכפול.
<br>
נראה דוגמא:



</p>

In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

In [ ]:
c @ mat

In [ ]:
d @ mat

In [ ]:
d.T @ mat

<p dir = rtl>

קרדיט לשי פרח על הגירסה מקורית של המחברת הזו
</p>